server:
  port: 82
spring:
  application:
    name: cloud-consumer-order81
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

