server:
  port: 8004
spring:
  application:
    name: cloud-payment-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/clouddb?useSSL=false&serverTimezone=UTC
  cloud:
    zookeeper:
      connect-string: 192.168.56.10:2181
mybatis:
  type-aliases-package: com.hdxy.pay.pojo
  mapper-locations: classpath:mapper/*.xml
